// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2KbtB6zid8MvjW-5Cyjg83YcVHBF-6mg',
    appId: '1:443840733284:web:4b005e0d79416d505fff71',
    messagingSenderId: '443840733284',
    projectId: 'food-store-680a4',
    authDomain: 'food-store-680a4.firebaseapp.com',
    storageBucket: 'food-store-680a4.firebasestorage.app',
    measurementId: 'G-1PWCK14MYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6wLCUHlp0xSN1JSoagaXOuahJ65-JPLI',
    appId: '1:443840733284:android:987a77f50f80a9085fff71',
    messagingSenderId: '443840733284',
    projectId: 'food-store-680a4',
    storageBucket: 'food-store-680a4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgIa2-TUkDmmHUDljYbmBNGEpb8ezKKXE',
    appId: '1:443840733284:ios:488ba5ef4e1c0e6c5fff71',
    messagingSenderId: '443840733284',
    projectId: 'food-store-680a4',
    storageBucket: 'food-store-680a4.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgIa2-TUkDmmHUDljYbmBNGEpb8ezKKXE',
    appId: '1:443840733284:ios:488ba5ef4e1c0e6c5fff71',
    messagingSenderId: '443840733284',
    projectId: 'food-store-680a4',
    storageBucket: 'food-store-680a4.firebasestorage.app',
    iosBundleId: 'com.example.foodie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2KbtB6zid8MvjW-5Cyjg83YcVHBF-6mg',
    appId: '1:443840733284:web:8ecc531d9998699a5fff71',
    messagingSenderId: '443840733284',
    projectId: 'food-store-680a4',
    authDomain: 'food-store-680a4.firebaseapp.com',
    storageBucket: 'food-store-680a4.firebasestorage.app',
    measurementId: 'G-JXLG3EN7G1',
  );

}